### PR TITLE
WIP: Try to build wit han older version of libvips

### PR DESCRIPTION
**Pull request by hmaarrfk**
Rebuilding:
https://github.com/conda-forge/pyvips-feedstock/pull/12#issuecomment-975486957

- 8.9 unsolvable
- 8.10 Failed
- 8.11 working

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@kleisauke I'm not sure what is wrong with 8.10. It builds, but segfaults.

I loosened the pinnings on the run export
https://github.com/conda-forge/libvips-feedstock/pull/48

We should probably patch up older builds that depend on libvips to use the loosened exports.

**Comment by kleisauke** [comment]
It looks like it segfaults while importing pyvips. A GDB backtrace would be helpful, or maybe setting-up logging would help, for example this is what I see locally on a non-Conda environment (when installing pyvips against libvips 8.12, and then downgrading libvips to 8.10):
```bash
$ python3 -c "import logging;logging.basicConfig(level=logging.DEBUG);import pyvips"
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Module generated for libvips 8.12
DEBUG:pyvips:Linked to libvips 8.12
DEBUG:pyvips:Inited libvips
# After downgrading libvips to 8.10
$ python3 -c "import logging;logging.basicConfig(level=logging.DEBUG);import pyvips"
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Module generated for libvips 8.12
DEBUG:pyvips:Linked to libvips 8.10
DEBUG:pyvips:Binary module load failed: bad wrapper version
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fadbfe91cf8>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7fadc0c39ef0>
DEBUG:pyvips:Inited libvips
```

Perhaps the fall-back to ABI mode doesn't work on Conda? If so, then the libvips versions should indeed match during compile-time and run-time for API mode. We sanity-check this here:
https://github.com/libvips/pyvips/blob/caceec98fa7f63ae6bc7bcb991c2ec946b16554a/pyvips/__init__.py#L39-L40

**Comment by kleisauke** [comment]
It seems that it fails to load the ImageMagick dependency with libvips 8.10.
```
DEBUG:pyvips:Binary module load failed: libMagickCore-7.Q16HDRI.so.9: cannot open shared object file: No such file or directory
DEBUG:pyvips:Falling back to ABI mode
...
Segmentation fault
```

**Comment by kleisauke** [comment]
Although I'm not sure why it segfaults when that occurs. For example, when I test this locally:
```bash
$ ldd /usr/lib64/libvips.so.42 | grep Magick
        libMagickCore-6.Q16.so.7 => /lib64/libMagickCore-6.Q16.so.7 (0x00007f020c156000)
$ mv /lib64/libMagickCore-6.Q16.so.7 /lib64/libMagickCore-6.Q16.so.7.old
$ python3 -c "import logging;logging.basicConfig(level=logging.DEBUG);import pyvips"
DEBUG:pyvips:Binary module load failed: libMagickCore-6.Q16.so.7: cannot open shared object file: No such file or directory
DEBUG:pyvips:Falling back to ABI mode
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ImportError: libMagickCore-6.Q16.so.7: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/pyvips/__init__.py", line 71, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libMagickCore-6.Q16.so.7: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
$ mv /lib64/libMagickCore-6.Q16.so.7.old /lib64/libMagickCore-6.Q16.so.7
```

**Comment by hmaarrfk** [comment]
It might be that there is an issue with the package imagemagick. There used to be some undefined dependencies a year back, on glib

https://github.com/conda-forge/imagemagick-feedstock/issues/146

Though I'm not too sure. I'm going to try to rebuild this with the loosened libvips pinning.

**Comment by hmaarrfk** [comment]
I'm going to close this since it isn't something I'm too keen on debugging. Thank you or chiming in. I think we were able to improve the recipe for libvips with your knowledge.

There might be issues with imagemagick :/

**Comment by kleisauke** [comment]
No problem, I'm glad I could help.

**Pull request closed without merging**
